# Generated by Django 2.1.5 on 2019-12-10 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothe',
            fields=[
                ('clothe', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('아우터', '아우터'), ('상의', '상의'), ('하의', '하의'), ('원피스', '원피스'), ('신발', '신발')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('phone_num', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('get_message', models.SmallIntegerField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('nickname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('request_num', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('처리전', '처리 전'), ('처리중', '처리중'), ('처리완료', '처리 완료'), ('수거완료', '수거 완료')], max_length=5)),
                ('rqst_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('est_date', models.DateTimeField(null=True)),
                ('fin_date', models.DateTimeField(null=True)),
                ('rtrn_date', models.DateTimeField(null=True)),
                ('requirements', models.TextField(null=True)),
                ('price', models.IntegerField()),
                ('clothe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Clothe')),
                ('phone_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('수선', '수선'), ('세탁', '세탁')], max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Service'),
        ),
    ]
